name: recipe_finder
description: Recipe Finder.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0
  chopper: ^4.0.5
  logging: ^1.0.2
  provider: ^6.0.2
  equatable: ^2.0.3
  http: ^0.13.4
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  synchronized: ^3.0.0+2
  sqlbrite: ^2.2.0
  moor_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  chopper_generator: ^4.0.5
  moor_generator: ^4.6.0+1


flutter:


  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/


