name: recipe
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4


flutter:


  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/


